[setup]
systemPackages = ["gcc", "libffi", "gfortran", "pkg-config", "libxml2", "libxslt", "r-base", "r-dev"]

[install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "flask run --host=0.0.0.0 --port=${PORT:-5000}"
